apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-regcred
type: kubernetes.io/dockerconfigjson
data:
  .dockerconfigjson: {{ include "common.docker.config.json" ( dict "imageCredentials" .Values.global.imageCredentials) }}