apiVersion: v1
kind: Secret
metadata:
  name: vmbc-secret-replica-2-concord
data:
  # cert private keys
  {{ range $path, $_ := .Files.Glob "replica-2/config/concord/config-local/tls_certs/*/*.pem" }}
  {{- $path | replace "/" "-" }}: {{ $.Files.Get $path | b64enc }}
  {{ end }}
  # transaction signing public key
  {{ range $path, $_ := .Files.Glob "replica-2/config/concord/config-public/transaction_signing_keys/*/transaction_signing_pub.pem" }}
  {{- $path | replace "/" "-" }}: {{ $.Files.Get $path | b64enc }}
  {{ end }}
  # operator public key
  {{- $operatorpublickey := "replica-2/config/concord/config-public/operator_pub.pem" }}
  operator-public-key-file: {{ $.Files.Get $operatorpublickey | b64enc }}