apiVersion: v1
kind: Service
metadata:
  name: replica-1
  labels:
    app: replica-1-concord
spec:
  type: ClusterIP
  ports:
    - name: 'tcp-3501'
      port: 3501
      protocol: TCP
      targetPort: 3501
    - name: '5458'
      port: 5458
      protocol: TCP
      targetPort: 5458
  selector:
    app: replica-1-concord

