apiVersion: v1
kind: Service
metadata:
  # This service is exposed externally
  name: client-0-ethrpc
  labels:
    app: client-0-ethrpc
spec:
  type: LoadBalancer
  ports:
    - name: '8545'
      port: 8545
      protocol: TCP
      targetPort: 8545
    - name: '9000'
      port: 9000
      protocol: TCP
      targetPort: 9000
  selector:
    app: client-0-ethrpc