## @section Global parameters
## Global Docker image parameters
## Please, note that this will override the image parameters, including dependencies, configured to use the global value
## Current available global Docker image parameters: imageCredentials, image
##

## @param global.imageCredentials Global Docker image registry
##
global:
  # The credentials for the docker registry. If username/password/email are specified, a corresponding Secret is created.
  imageCredentials:
    registry: ""
    username: ""
    password: ""
    email: ""
  # The global artifact tag
  image:
    repository: "vmwblockchain/python"
    tag: "3.9.10"

## Configure the configmap parameters that allows you to link the blockchain ethrpc url
## @param blockchainUrl Url to link blockchain ethrpc with erc20 token transfer test
##
blockchainUrl: ""

## Configure the configmap parameters that allows you to pass the erc20 token transfer test
## @param testCount Number of transaction to initiate with erc20 token transfer test
##
testCount: 2

## Configure the resources for vmbc erc20 token transfer test
## @param resources Resources for vmbc erc20 token transfer test
##
resources:
  # @param test VMBC erc20 token transfer test
  test:
    cpuLimit: 100m
    cpuRequest: 100m
    memoryLimit: 1Gi
    memoryRequest: 1Gi
